version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: farpostbooks_telegram:${FARPOSTBOOKS_TELEGRAM_VERSION:-latest}
    volumes:
      - images:/app/src/images
    env_file:
      - .env
    restart: always
    networks:
      - farpostbooks_backend_backnet

networks:
  farpostbooks_backend_backnet:
    external: true

volumes:
  images:
    external: true
